openapi: 3.0.3
info:
  title: KPNP - 품새 API
  version: 0.0.1
servers:
  - url: https://dev.kpnpglobal.com:9143/api/champs/ps/v1
tags:
  - name: 대회개최
  - name: 공통

paths:
  /competitions/default:
    get:
      summary: 기본 정보 설정 조회 (기본 값)
      tags:
        - 대회개최
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  divisionList:
                    type: array
                    description: 대회룰 그룹 리스트
                    items:
                      type: object
                      properties:
                        divisionSeq:
                          type: number
                        divisionCode:
                          type: string
                          example: "00"
                        divisionNameEn:
                          type: string
                          example: "WT Recognized Poomsae"
                        divisionNameKo:
                          type: string
                          example: "WT 공인품새룰"
                  countryList:
                    type: array
                    description: 국가 코드 리스트
                    items:
                      type: object
                      properties:
                        codeDetailNo:
                          type: string
                          example: "AF"
                        codeDetailName:
                          type: string
                          example: "(+93) Afghanistan"
                  utcList:
                    type: array
                    description: UTC 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "KOR"
                        nameEn:
                          type: string
                          example: "Korea (Seoul)"
                        subCode1:
                          type: string
                          example: "(Seoul)"
                        exp1:
                          type: string
                          example: "+0000"
                        utcInfo:
                          type: string
                          example: "(UTC +04:30)"
                  wtClassList:
                    type: array
                    description: WT 코드 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "G1"
                  bankList:
                    type: array
                    description: 은행 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        nameEn:
                          type: string
                          example: "BankOfChina"
                        nameKo:
                          type: string
                          example: "중국은행"
                  poomsaeList:
                    type: array
                    description: 품새 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        nameEn:
                          type: string
                          example: "Taegeuk 1 Jang"
                        nameKo:
                          type: string
                          example: "태극 1장"
                  compositeRateList:
                    type: array
                    description: 복합품새 비중 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        nameEn:
                          type: string
                          example: "공인10:자유90"
                        nameKo:
                          type: string
                          example: "공인10:자유90"
                  matchOrderList:
                    type: array
                    description: 품새 경기 순서 코드 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        nameEn:
                          type: string
                          example: "Chung-Chung-Hong-Hong"
                        nameKo:
                          type: string
                          example: "청-청-홍-홍"
                  poomsaeDrawList:
                    type: array
                    description: 품새 추첨 방식 리스트
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        nameEn:
                          type: string
                        nameKo:
                          type: string
    post:
      summary: 기본 정보 설정 등록/수정
      tags:
        - 대회개최
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hostDivisionList:
                  type: array
                  items:
                    type: object
                    properties:
                      divisionSeq:
                        type: number
                      delDivisionUsedSeq:
                        type: number
                hostDefaultInfo:
                  type: object
                  properties:
                    competitionSeq:
                      type: number
                      example: 1
                    competitionDiscipline:
                      type: string
                      example: "Taekwondo Poomsae"
                    competitionNameKo:
                      type: string
                      example: "테스트대회"
                    competitionNameEn:
                      type: string
                      example: "Test"
                    competitionContent:
                      type: string
                      example: "대회소개6"
                    competitionHostName:
                      type: string
                      example: "호스트"
                    competitionHostCountry:
                      type: string
                      example: "KR"
                    competitionHostCall:
                      type: string
                      example: "01075345140"
                    competitionSdate:
                      type: string
                      format: date-time
                      example: "2025-02-10T09:00:00.000Z"
                    competitionEdate:
                      type: string
                      format: date-time
                      example: "2025-02-20T23:00:00.000Z"
                    competitionLocationKo:
                      type: string
                      example: "부산"
                    competitionLocationEn:
                      type: string
                      example: "Busan"
                    competitionUtcCode:
                      type: string
                      example: "KOR"
                    competitionSubSdate:
                      type: string
                      format: date-time
                      example: "2025-02-01T15:00:00.000Z"
                    competitionSubEdate:
                      type: string
                      format: date-time
                      example: "2025-02-02T23:00:00.000Z"
                    competitionLocalYn:
                      type: string
                      example: "W"
                    competitionWtCodeSendYn:
                      type: string
                      example: "Y"
                    competitionWtClassCode:
                      type: string
                      example: "G1"
                    competitionParticipantPayYn:
                      type: string
                      example: "N"
                    bankName:
                      type: string
                      example: ""
                    accountNumber:
                      type: string
                      example: ""
                    accountHolderName:
                      type: string
                      example: ""
                    competitionParticipantPay:
                      type: string
                      example: ""
                    scoreDevice:
                      type: string
                      example: "D"
                    delS3MediaSeq:
                      type: string
                      description: 삭제할 이미지 및 파일 seq 목록 (comma-separated)
                      example: "71,72,74"
                    delS3MediaSeqSortNo:
                      type: string
                      description: 삭제할 이미지 및 파일 순서 목록 (comma-separated)
                      example: "2,3,1"
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/responses/OK'
              examples:
                success:
                  value:
                    success: true
                    data: "competitionSeq : 63"
                    error: null
                NO_COMPETITION:
                  $ref: '#/components/examples/NO_COMPETITION'
        500:
          description: 실패
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Error'
              examples:
                FILE_TRANSFER_TO_S3_ERROR:
                  $ref: '#/components/examples/FILE_TRANSFER_TO_S3_ERROR'

  /competitions/default/{competitionSeq}:
    get:
      summary: 기본 정보 설정 조회 (유저 입력값)
      tags:
        - 대회개최
      parameters:
        - name: competitionSeq
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCompetitionDefaultResponse'

  /competitions/media:
    post:
      summary: 기본 정보 설정 파일 저장
      tags:
        - 대회개최
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                competitionSeq:
                  type: number
                  example: 13
                  description: 대회 seq
                mediaList:
                  type: array
                  items:
                    type: object
                    properties:
                      mediaInfo:
                        type: string
                        format: binary
                        description: 업로드할 파일 (MultipartFile)
                      mediaCategory:
                        type: string
                        example: "M"
                        description: "미디어 구분 (메인사진: M, 파일: F, 대회로고: CR, 주최로고: HR, 배너이미지: BI, 스폰서: S)"
                      sortNo:
                        type: number
                        example: 1
                        description: 파일 순서
                mediaList[0].mediaInfo:
                  type: string
                  format: binary
                  description: 업로드할 파일 (MultipartFile)
                mediaList[0].mediaCategory:
                  $ref: '#/components/schemas/MediaType'
                mediaList[0].sortNo:
                  type: integer
                  description: 파일 정렬 순서
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/responses/OK'
              examples:
                success:
                  value:
                    success: true
                    data: "competitionSeq : 63"
                    error: null
                NO_COMPETITION:
                  $ref: '#/components/examples/NO_COMPETITION'
        500:
          description: 실패
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Error'
              examples:
                FILE_TRANSFER_TO_S3_ERROR:
                  $ref: '#/components/examples/FILE_TRANSFER_TO_S3_ERROR'

  /common/combo/rules:
    get:
      summary: 품새 대회룰 조회
      tags:
        - 공통
      responses:
        '200':
          description: 성공적으로 조회된 응답
          content:
            application/json:
              examples:
                divisionRulesExample:
                  summary: example
                  value:
                    success: true
                    data:
                      rules:
                        - poomsaeDivisionType: WT_RECOGNIZED_POOMSAE
                          nameEn: WT Recognized Poomsae
                          nameKo: WT 공인품새룰
                        - poomsaeDivisionType: FREE_STYLE_POOMSAE
                          nameEn: Free Style Poomsae
                          nameKo: 자유품새룰
                        - poomsaeDivisionType: MIXED_POOMSAE
                          nameEn: Mixed Poomsae
                          nameKo: 복합품새룰
                        - poomsaeDivisionType: KVR_RECOGNIZED_POOMSAE
                          nameEn: KVR Recognized Poomsae
                          nameKo: 한국 공인품새룰
                        - poomsaeDivisionType: OPEN_RECOGNIZED_POOMSAE
                          nameEn: Open Recognized Poomsae
                          nameKo: 오픈대회 공인품새
                        - poomsaeDivisionType: OPEN_FREE_STYLE_POOMSAE
                          nameEn: Open Free Style Poomsae
                          nameKo: 오픈대회 자유품새
                    error: null

  /common/combo/countries:
    get:
      summary: 국가 조회 (+연락처)
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      countries:
                        type: array
                        items:
                          $ref: '#/components/schemas/Country'
              example:
                success: true
                data:
                  countries:
                    - codeDetailNo: "AF"
                      codeDetailName: "(+93) Afghanistan"
                    - codeDetailNo: "AL"
                      codeDetailName: "(+355) Albania"
                    - codeDetailNo: "DZ"
                      codeDetailName: "(+213) Algeria"
                    - codeDetailNo: "AS"
                      codeDetailName: "(+1-684) American Samoa"
                    - codeDetailNo: "AD"
                      codeDetailName: "(+376) Andorra"
                    - codeDetailNo: "AO"
                      codeDetailName: "(+244) Angola"
                    - codeDetailNo: "AI"
                      codeDetailName: "(+1-264) Anguilla"
                    - codeDetailNo: "AQ"
                      codeDetailName: "(+672) Antarctica"
                    - codeDetailNo: "AG"
                      codeDetailName: "(+1-268) Antigua and Barbuda"
                    - codeDetailNo: "AR"
                      codeDetailName: "(+54) Argentina"
                    - codeDetailNo: "AM"
                      codeDetailName: "(+374) Armenia"
                    - codeDetailNo: "AW"
                      codeDetailName: "(+297) Aruba"
                    - codeDetailNo: "AU"
                      codeDetailName: "(+61) Australia"
                    - codeDetailNo: "AT"
                      codeDetailName: "(+43) Austria"
                    - codeDetailNo: "AZ"
                      codeDetailName: "(+994) Azerbaijan"

  /common/combo/noc-list:
    get:
      summary: 국가 조회 (+표준시간)
      tags:
        - 공통
      responses:
        '200':
          description: 성공적으로 NOC 리스트 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      nocList:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              example: "KSA"
                            nameEn:
                              type: string
                              example: "Saudi Arabia"
                            utcInfo:
                              type: string
                              example: "(UTC +03:00)"
                        example:
                          - code: "KSA"
                            nameEn: "Saudi Arabia"
                            utcInfo: "(UTC +03:00)"
                          - code: "LAT"
                            nameEn: "Latvia"
                            utcInfo: "(UTC +02:00)"
                          - code: "LBA"
                            nameEn: "Libya"
                            utcInfo: "(UTC +02:00)"
                          - code: "MAD"
                            nameEn: "Madagascar"
                            utcInfo: "(UTC +03:00)"
                          - code: "MAS"
                            nameEn: "Malaysia"
                            utcInfo: "(UTC +08:00)"
                  error:
                    type: string
                    example: null
                    nullable: true

  /common/combo/wt-grades:
    get:
      summary: WT Grades 조회
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      poomsaeWTGradeTypeList:
                        type: array
                        items:
                          type: string
                        example: [ "G1", "G2", "G4", "G6", "G8", "G10" ]
                  error:
                    type: string
                    nullable: true
                    example: null

  /common/combo/poomsae-list:
    get:
      summary: 품새 항목 조회
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      poosaeList:
                        type: array
                        items:
                          type: object
                          properties:
                            poomsaeType:
                              type: string
                              example: "TAEGEUK_1_JANG"
                            nameEn:
                              type: string
                              example: "Taegeuk 1 Jang"
                            nameKo:
                              type: string
                              example: "태극 1장"
                        example:
                          - poomsaeType: "TAEGEUK_1_JANG"
                            nameEn: "Taegeuk 1 Jang"
                            nameKo: "태극 1장"
                          - poomsaeType: "TAEGEUK_2_JANG"
                            nameEn: "Taegeuk 2 Jang"
                            nameKo: "태극 2장"
                          - poomsaeType: "TAEGEUK_3_JANG"
                            nameEn: "Taegeuk 3 Jang"
                            nameKo: "태극 3장"
                          - poomsaeType: "TAEGEUK_4_JANG"
                            nameEn: "Taegeuk 4 Jang"
                            nameKo: "태극 4장"
                          - poomsaeType: "KORYO"
                            nameEn: "Koryo"
                            nameKo: "고려"
                          - poomsaeType: "HANSU"
                            nameEn: "Hansu"
                            nameKo: "한수"
                  error:
                    type: string
                    nullable: true
                    example: null

  /common/combo/composite-rate-List:
    get:
      summary: 품새 항목 조회
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      compositeRateList:
                        type: array
                        items:
                          type: object
                          properties:
                            poomsaeCompositeRateType:
                              type: string
                              example: "D0"
                            nameKo:
                              type: string
                              example: "공인10:자유90"
                        example:
                          - poomsaeCompositeRateType: "D0"
                            nameKo: "공인10:자유90"
                          - poomsaeCompositeRateType: "D4"
                            nameKo: "공인50:자유50"
                          - poomsaeCompositeRateType: "D8"
                            nameKo: "공인90:자유10"
                  error:
                    type: string
                    nullable: true
                    example: null

  /common/combo/match-orders:
    get:
      summary: 품새 시연 순서 목록
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      matchOrders:
                        type: array
                        items:
                          type: object
                          properties:
                            poomsaeMatchOrderType:
                              type: string
                              example: "CHUNG_CHUNG_HONG_HONG"
                            nameEn:
                              type: string
                              example: "Chung-Chung-Hong-Hong"
                            nameKo:
                              type: string
                              example: "청-청-홍-홍"
                        example:
                          - poomsaeMatchOrderType: "CHUNG_CHUNG_HONG_HONG"
                            nameEn: "Chung-Chung-Hong-Hong"
                            nameKo: "청-청-홍-홍"
                          - poomsaeMatchOrderType: "HONG_HONG_CHUNG_CHUNG"
                            nameEn: "Hong-Hong-Chung-Chung"
                            nameKo: "홍-홍-청-청"
                          - poomsaeMatchOrderType: "CHUNG_HONG_CHUNG_HONG"
                            nameEn: "Chung-Hong-Chung-Hong"
                            nameKo: "청-홍-청-홍"
                          - poomsaeMatchOrderType: "HONG_CHUNG_HONG_CHUNG"
                            nameEn: "Hong-Chung-Hong-Chung"
                            nameKo: "홍-청-홍-청"
                          - poomsaeMatchOrderType: "TOGETHER"
                            nameEn: "Together"
                            nameKo: "함께시연"
                  error:
                    type: string
                    nullable: true
                    example: null

  /common/combo/draw-list:
    get:
      summary: 품새 추첨 방식 목록 조회
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      drawList:
                        type: array
                        items:
                          type: object
                          properties:
                            poomsaeDrawType:
                              type: string
                              example: RANDOM
                              description: 품새 추첨 방식 코드
                            nameEn:
                              type: string
                              example: Random
                              description: 영어 이름
                            nameKo:
                              type: string
                              example: 무작위
                              description: 한국어 이름
                          example:
                            - poomsaeDrawType: RANDOM
                              nameEn: Random
                              nameKo: 무작위
                            - poomsaeDrawType: PIN_SELECT
                              nameEn: PinSelect
                              nameKo: 고정선택
                            - poomsaeDrawType: REFEREE_SELECT
                              nameEn: RefereeSelect
                              nameKo: 심판추첨
                  error:
                    type: object
                    nullable: true
                    example: null

  /common/combo/bank-list:
    get:
      summary: 은행 목록 조회
      tags:
        - 공통
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      bankList:
                        type: array
                        items:
                          type: object
                          properties:
                            codeDetailNo:
                              type: string
                              example: BKCHCNBJ
                              description: 은행 코드
                            codeDetailName:
                              type: string
                              example: BankOfChina
                              description: 은행 영문명
                            description:
                              type: string
                              example: 중국은행
                              description: 은행 한글 설명
                            subCodeNo:
                              type: string
                              example: CN
                              description: 국가 코드
                          example:
                            - codeDetailNo: BKCHCNBJ
                              codeDetailName: BankOfChina
                              description: 중국은행
                              subCodeNo: CN
                            - codeDetailNo: ICBKCNBJ
                              codeDetailName: Industrial and Commercial Bank of China
                              description: 중국공상은행
                              subCodeNo: CN
                            - codeDetailNo: PBOCCNBJ
                              codeDetailName: Peoples Bank of China
                              description: 중국인민은행
                              subCodeNo: CN
                            - codeDetailNo: SHBKKRSEXXX
                              codeDetailName: ShinhanBank
                              description: 신한은행
                              subCodeNo: KR
                  error:
                    type: object
                    nullable: true
                    example: null
components:
  responses:
    OK:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              data:
                type: string
                example: null
              error:
                type: string
                example: null
    Error:
      description: error operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              data:
                type: string
                example: null
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: "내부 오류 발생"
                  errorCode:
                    type: string
                    example: "500"
  examples:
    # 200
    NO_COMPETITION:
      value:
        success: true
        data: null
        error:
          message: "파일 업로드 중 네트워크 오류 발생."
          errorCode: "E010"
    # 500
    FILE_TRANSFER_TO_S3_ERROR:
      value:
        success: false
        data: null
        error:
          message: "파일 S3에 전송 중 오류 발생."
          errorCode: "E009"

  schemas:
    getCompetitionDefaultResponse:
      properties:
        divisionList:
          type: array
          items:
            type: object
            properties:
              divisionSeq:
                type: number
                example: 623
              divisionCode:
                type: string
                example: "00"
              divisionNameEn:
                type: string
                example: "WT Recognized Poomsae"
              divisionNameKo:
                type: string
                example: "WT 공인품새룰"
        countryList:
          type: array
          items:
            type: object
            properties:
              codeDetailNo:
                type: string
                example: "AF"
              codeDetailName:
                type: string
                example: "(+93) Afghanistan"
        utcList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "COK"
              nameEn:
                type: string
                example: "Cook Islands"
              subCode1:
                type: string
                example: null
              exp1:
                type: string
                example: "-1000"
              utcInfo:
                type: string
                example: "(UTC -10:00)"
        wtClassList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "G1"
        bankList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "BFTVVNVX"
              nameEn:
                type: string
                example: "VietcomBank"
              nameKo:
                type: string
                example: "비엣콤 은행"
        poomsaeList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "C00"
              nameEn:
                type: string
                example: "Taegeuk 1 Jang"
              nameKo:
                type: string
                example: "태극 1장"
        compositeRateList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "D0"
              nameEn:
                type: string
                example: null
              nameKo:
                type: string
                example: "공인10:자유90"
        matchOrderList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "E1"
              nameEn:
                type: string
                example: "Chung-Chung-Hong-Hong"
              nameKo:
                type: string
                example: "청-청-홍-홍"
        poomsaeDrawList:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "H"
              nameEn:
                type: string
                example: "PinSelect"
              nameKo:
                type: string
                example: "고정선택"
        hostDefaultInfo:
          type: object
          properties:
            competitionNameKo:
              type: string
              example: "정수의 WT공인품새 테스트대회"
            competitionNameEn:
              type: string
              example: "Test"
            competitionContent:
              type: string
              example: "정수대회소개임ㅋㅋㅋ"
            competitionHostName:
              type: string
              example: "호스트"
            competitionHostCountry:
              type: string
              example: "KR"
            competitionHostCall:
              type: string
              example: "01075345140"
            competitionSdate:
              type: string
              format: date-time
              example: "2025-02-23 00:00:00.0"
            competitionEdate:
              type: string
              format: date-time
              example: "2025-03-10 23:59:00.0"
            competitionLocationKo:
              type: string
              example: "부산"
            competitionLocationEn:
              type: string
              example: "Busan"
            competitionUtcCode:
              type: string
              example: "KOR"
            competitionSubSdate:
              type: string
              format: date-time
              example: "2025-02-19 00:00:00.0"
            competitionSubEdate:
              type: string
              format: date-time
              example: "2025-02-22 23:59:00.0"
            competitionLocalYn:
              type: string
              example: "W"
            competitionWtCodeSendYn:
              type: string
              example: "Y"
            competitionWtClassCode:
              type: string
              example: "G1"
            competitionParticipantPayYn:
              type: string
              example: "N"
            bankName:
              type: string
              example: null
            accountNumber:
              type: string
              example: null
            accountHolderName:
              type: string
              example: null
            competitionParticipantPay:
              type: string
              example: "N"
            orderStatus:
              type: string
              example: null
            scoreDevice:
              type: string
              example: "D"
        hostDivisionList:
          type: array
          items:
            type: object
            properties:
              divisionSeq:
                type: number
                example: 623
              delDivisionUsedSeq:
                type: number
                example: 14
        hostMainImgList:
          type: array
          items:
            type: object
            properties:
              s3MediaSeq:
                type: number
                example: 219
              s3CdnUrl:
                type: string
                example: "https://cdn.kpnpglobal.com/kpnp/media/image/champs/2024/02/fa418844fa014a819d7e7e38e08d0311.JPEG"
              mediaType:
                type: string
                example: "I"
              originName:
                type: string
                example: "테스트 이미지.jpeg"
              fileSize:
                type: string
                example: "6"
              sortNo:
                type: number
                example: 2
        hostFileList:
          type: array
          items:
            type: object
            properties:
              s3MediaSeq:
                type: number
                example: 220
              s3CdnUrl:
                type: string
                example: "https://cdn.kpnpglobal.com/kpnp/media/file/champs/2024/02/308614928b5b477db2ec949cdbcad063.TXT"
              mediaType:
                type: string
                example: "F"
              originName:
                type: string
                example: "테스트 파일 - 복사본.txt"
              fileSize:
                type: string
                example: "0"
              sortNo:
                type: number
                example: 2
    Country:
      type: object
      properties:
        codeDetailNo:
          type: string
          example: "AF"
        codeDetailName:
          type: string
          example: "(+93) Afghanistan"
    # Enums
    MediaType:
      type: string
      description: 미디어 구분
      enum:
        - M (메인사진)
        - F (파일)
        - CR (대회로고)
        - HR (주최로고)
        - BI (베너이미지)
        - S (스폰서)
